"""Track id is string in skipped class

Revision ID: 03833c502471
Revises: b7a0f696dfad
Create Date: 2023-10-12 15:17:57.271137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03833c502471'
down_revision = 'b7a0f696dfad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped', schema=None) as batch_op:
        batch_op.alter_column('track_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped', schema=None) as batch_op:
        batch_op.alter_column('track_id',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
