"""total played

Revision ID: 174473f0a482
Revises: 716c3359fcee
Create Date: 2023-10-18 21:07:44.808206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174473f0a482'
down_revision = '716c3359fcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_played', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_played')

    # ### end Alembic commands ###
