"""profile pic

Revision ID: 20409b62ee82
Revises: 271eda971de1
Create Date: 2023-12-12 16:20:39.093083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20409b62ee82'
down_revision = '271eda971de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
