"""select

Revision ID: 271eda971de1
Revises: f94795b62035
Create Date: 2023-10-27 14:54:09.512554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271eda971de1'
down_revision = 'f94795b62035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected', sa.Boolean(), nullable=True))
        batch_op.drop_column('slected')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slected', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('selected')

    # ### end Alembic commands ###
