"""delete playlist_id from queue

Revision ID: 716c3359fcee
Revises: bb7f9fe9c609
Create Date: 2023-10-16 17:13:28.408441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716c3359fcee'
down_revision = 'bb7f9fe9c609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prev_queue', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prev_queue_playlist_id_playlist', type_='foreignkey')
        batch_op.drop_column('playlist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prev_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_prev_queue_playlist_id_playlist', 'playlist', ['playlist_id'], ['id'])

    # ### end Alembic commands ###
