"""user_id in skipped class

Revision ID: a2ac4ca797e0
Revises: 03833c502471
Create Date: 2023-10-12 16:44:42.712661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ac4ca797e0'
down_revision = '03833c502471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('track_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_skipped_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_skipped_user_id_user'), type_='foreignkey')
        batch_op.alter_column('track_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
