"""Add playlist_id to prev_queue

Revision ID: bb7f9fe9c609
Revises: e1ac4b5f3570
Create Date: 2023-10-16 16:52:32.438677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7f9fe9c609'
down_revision = 'e1ac4b5f3570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prev_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_prev_queue_playlist_id_playlist'), 'playlist', ['playlist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prev_queue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_prev_queue_playlist_id_playlist'), type_='foreignkey')
        batch_op.drop_column('playlist_id')

    # ### end Alembic commands ###
