"""Optimize skipped

Revision ID: bf820f9391c3
Revises: a7dbab6880f7
Create Date: 2023-10-09 03:54:27.782589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf820f9391c3'
down_revision = 'a7dbab6880f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skipped',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('skipped_once')
    op.drop_table('skipped_twice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skipped_twice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=True),
    sa.Column('playlist_id', sa.VARCHAR(length=120), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skipped_once',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=True),
    sa.Column('playlist_id', sa.VARCHAR(length=120), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('skipped')
    # ### end Alembic commands ###
