"""OAuth backref and set token function

Revision ID: cfbce923e5c0
Revises: 4ec5fe6596b1
Create Date: 2023-10-10 02:27:00.620180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfbce923e5c0'
down_revision = '4ec5fe6596b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('prev_queue')
    op.drop_table('oauth')
    op.drop_table('skipped')
    op.drop_table('playlist')
    op.drop_table('track')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('playlist_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name='fk_track_playlist_id_playlist'),
    sa.PrimaryKeyConstraint('id', name='pk_track')
    )
    op.create_table('playlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_playlist_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_playlist')
    )
    op.create_table('skipped',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('skipped_count', sa.INTEGER(), nullable=True),
    sa.Column('track_id', sa.INTEGER(), nullable=True),
    sa.Column('playlist_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name='fk_skipped_playlist_id_playlist'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name='fk_skipped_track_id_track'),
    sa.PrimaryKeyConstraint('id', name='pk_skipped')
    )
    op.create_table('oauth',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=120), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=120), nullable=True),
    sa.Column('expires_at', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_oauth_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_oauth')
    )
    op.create_table('prev_queue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=True),
    sa.Column('queue_index', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name='fk_prev_queue_track_id_track'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_prev_queue_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_prev_queue')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=120), nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=120), nullable=True),
    sa.Column('currently_listening', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user')
    )
    # ### end Alembic commands ###
