"""change track_id to string

Revision ID: f673911a010c
Revises: a2ac4ca797e0
Create Date: 2023-10-12 17:43:29.527847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f673911a010c'
down_revision = 'a2ac4ca797e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped', schema=None) as batch_op:
        batch_op.alter_column('track_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skipped', schema=None) as batch_op:
        batch_op.alter_column('track_id',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
